# Generated by Django 6.0.4 on 2026-05-04 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=12)),
                ('montant_total', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('date_vente', models.DateTimeField(auto_now_add=True)),
                ('client', models.CharField(blank=True, max_length=200)),
                ('annulee', models.BooleanField(default=False)),
                ('gestionnaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventes', to=settings.AUTH_USER_MODEL)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventes', to='produits.produit')),
            ],
            options={
                'verbose_name': 'Vente',
                'ordering': ['-date_vente'],
            },
        ),
    ]
